# -*- coding: utf-8 -*-
"""
Created on Tue Jul 14 11:24:43 2020

@author: rober
"""
import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np
import seaborn as sns
import matplotlib.ticker as ticker


path = os.getcwd()

# making data frame  
print(path)
df = pd.read_excel('PAA soft and stiff gels_20221025_AriellSmith.xlsx')


#plotting the data in a scatter plot
######################## 10.22.2022################
#d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_soft gels allowed to polymerize between plates_ test conducted 20221022_sample1 [rad/s]', y = ' Storage Modulus_soft gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221022_sample1 [Pa]', data = df, color = 'red', marker = 'o', edgecolor = 'red', label = 'G\u2032, Soft PAH_S1')
#d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_soft gels allowed to polymerize between plates_ test conducted 20221022_sample1 [rad/s]', y = ' Loss Modulus_soft gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221022_sample1 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'red', label = 'G\u2032\u2032, Soft PAH_S1')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_soft gels allowed to polymerize between plates_ test conducted 20221022_sample1 [%]', y = ' Storage Modulus_soft gels_ allowed to polymerize between plate_ constant frequency 1 Hz_test conducted 20221022_sample1 [Pa]', data = df, color = 'red', marker = 'o', edgecolor = 'red', label = 'G\u2032, Soft PAH_S1')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_soft gels allowed to polymerize between plates_ test conducted 20221022_sample1 [%]', y = 'Loss Modulus_soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221022_sample1 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'red', label = 'G\u2032\u2032, Soft PAH_S1')

#d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_soft gels allowed to polymerize between plates_ test conducted 20221022_sample2 [rad/s]', y = ' Storage Modulus_soft gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221022_sample2 [Pa]', data = df, color = 'black', marker = 'o', edgecolor = 'black', label = 'G\u2032, Soft PAH_S2')
#d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_soft gels allowed to polymerize between plates_ test conducted 20221022_sample2 [rad/s]', y = ' Loss Modulus_soft gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221022_sample2 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'black', label = 'G\u2032\u2032, Soft PAH_S2')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_soft gels allowed to polymerize between plates_ test conducted 20221022_sample2 [%]', y = ' Storage Modulus_soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221022_sample2 [Pa]', data = df, color = 'black', marker = 'o', edgecolor = 'black', label = 'G\u2032, Soft PAH_S2')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_soft gels allowed to polymerize between plates_ test conducted 20221022_sample2 [%]', y = 'Loss Modulus_soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221022_sample2 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'black', label = 'G\u2032\u2032, Soft PAH_S2')

#d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_soft gels allowed to polymerize between plates_ test conducted 20221022_sample3 [rad/s]', y = ' Storage Modulus_soft gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221022_sample3 [Pa]', data = df, color = 'orange', marker = 'o', edgecolor = 'orange', label = 'G\u2032, Soft PAH_S3')
#d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_soft gels allowed to polymerize between plates_ test conducted 20221022_sample3 [rad/s]', y = 'Loss Modulus_soft gels_ allowed to polymerize between plate_constant strain 1%_ test conducted 20221022_sample3 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'orange', label = 'G\u2032\u2032, Soft PAH_S3')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_soft gels allowed to polymerize between plates_ test conducted 20221022_sample3 [%]', y = ' Storage Modulus_soft gels_ allowed to polymerize between plate_ constant frequency 1 Hz_test conducted 20221022_sample3 [Pa]', data = df, color = 'orange', marker = 'o', edgecolor = 'orange', label = 'G\u2032,  Soft PAH_S3')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_soft gels allowed to polymerize between plates_ test conducted 20221022_sample3 [%]', y = 'Loss Modulus_soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221022_sample3 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'orange', label = 'G\u2032\u2032,  Soft PAH_S3')

########################### AVERAGE OF ONLY FREQUENCY SWEEP FOR SOFT, INTERMEDIATE,and STIFF########################
d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_stiff gels allowed to polymerize between plates_ test conducted 20221025_average of all stiff PAH samples [rad/s]', y = 'Storage Modulus_stiff gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221025_average of all stiff PAH samples [Pa]', data = df, color = 'red', marker = 'o', edgecolor = 'red', label = 'G\u2032, Stiff PAH')
d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_stiff gels allowed to polymerize between plates_ test conducted 20221025_average of all stiff PAH samples [rad/s]', y = 'Loss Modulus_stiff gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221025_average of all stiff PAH samples [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'red', label = 'G\u2032\u2032, Stiff PAH')
d_fn.errorbar(x = 'Frequency sweep_0.1-200 rads/s_stiff gels allowed to polymerize between plates_ test conducted 20221025_average of all stiff PAH samples [rad/s]', y = 'Storage Modulus_stiff gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221025_average of all stiff PAH samples [Pa]', yerr = 'Storage Modulus_stiff gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221025_STDDEV of all stiff PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'red')
d_fn.errorbar(x = 'Frequency sweep_0.1-200 rads/s_stiff gels allowed to polymerize between plates_ test conducted 20221025_average of all stiff PAH samples [rad/s]', y = 'Loss Modulus_stiff gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221025_average of all stiff PAH samples [Pa]', yerr = 'Loss Modulus_stiff gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221025_STDDEV of all stiff PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'red')
d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_intermediate gels allowed to polymerize between plates_ test conducted 20221128_average of all intermediate PAH samples [rad/s]', y = 'Storage Modulus_intermediate elastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221128_average of all intermediate elastic PAH samples [Pa]', data = df, color = 'black', marker = 'o', edgecolor = 'blue', label = 'G\u2032, intermediate PAH')
d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_intermediate gels allowed to polymerize between plates_ test conducted 20221128_average of all intermediate PAH samples [rad/s]', y = 'Loss Modulus_intermediate elastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221128_average of all intermediate elastic PAH samples [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'blue', label = 'G\u2032\u2032, intermediate PAH')
d_fn.errorbar(x = 'Frequency sweep_0.1-200 rads/s_intermediate gels allowed to polymerize between plates_ test conducted 20221128_average of all intermediate PAH samples [rad/s]', y = 'Storage Modulus_intermediate elastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221128_average of all intermediate elastic PAH samples [Pa]', yerr = 'Storage Modulus_intermediate elastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221128_STDDEV of all intermediate elastic PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'blue')
d_fn.errorbar(x = 'Frequency sweep_0.1-200 rads/s_intermediate gels allowed to polymerize between plates_ test conducted 20221128_average of all intermediate PAH samples [rad/s]', y = 'Loss Modulus_intermediate elastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221128_average of all intermediate elastic PAH samples [Pa]', yerr = 'Loss Modulus_intermediate elastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221128_STDDEV of all intermediate elastic PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'blue')
d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_soft gels allowed to polymerize between plates_ test conducted 20221022_average of all soft PAH samples [rad/s]', y = 'Storage Modulus_soft gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221022_average of all soft PAH samples [Pa]', data = df, color = 'black', marker = 'o', edgecolor = 'black', label = 'G\u2032, Soft PAH')
d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_soft gels allowed to polymerize between plates_ test conducted 20221022_average of all soft PAH samples [rad/s]', y = 'Loss Modulus_soft gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221022_average of all soft PAH samples [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'black', label = 'G\u2032\u2032, Soft PAH')
d_fn.errorbar(x = 'Frequency sweep_0.1-200 rads/s_soft gels allowed to polymerize between plates_ test conducted 20221022_average of all soft PAH samples [rad/s]', y = 'Storage Modulus_soft gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221022_average of all soft PAH samples [Pa]', yerr = 'Storage Modulus_soft gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221022_STDDEV of all soft PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'black')
d_fn.errorbar(x = 'Frequency sweep_0.1-200 rads/s_soft gels allowed to polymerize between plates_ test conducted 20221022_average of all soft PAH samples [rad/s]', y = 'Loss Modulus_soft gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221022_average of all soft PAH samples [Pa]', yerr = 'Loss Modulus_soft gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221022_STDDEV of all soft PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'black')



########################### AVERAGE OF ONLY STRAIN SWEEP FOR SOFT, INTERMEDIATE, AND STIFF########################
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_stiff gels allowed to polymerize between plates_ test conducted 20221027_Average of all stiff PAH samples [%]', y = 'Storage Modulus_stiff gels_ allowed to polymerize between plate_ test conducted 20221027_average of all stiff PAH samples [Pa]', data = df, color = 'red', marker = 'o', edgecolor = 'red', label = 'G\u2032, Stiff PAH')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_stiff gels allowed to polymerize between plates_ test conducted 20221027_Average of all stiff PAH samples [%]', y = 'Loss Modulus_stiff gels_ allowed to polymerize between plate_ test conducted 20221027_average of all stiff PAH samples [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'red', label = 'G\u2032\u2032, Stiff PAH')
#d_fn.errorbar(x = 'Shear Strain in percent_stiff gels allowed to polymerize between plates_ test conducted 20221027_Average of all stiff PAH samples [%]', y = 'Storage Modulus_stiff gels_ allowed to polymerize between plate_ test conducted 20221027_average of all stiff PAH samples [Pa]', yerr = 'Storage Modulus_stiff gels_ allowed to polymerize between plate_ test conducted 20221027_STDDEV of all stiff PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'red')
#d_fn.errorbar(x = 'Shear Strain in percent_stiff gels allowed to polymerize between plates_ test conducted 20221027_Average of all stiff PAH samples [%]', y = 'Loss Modulus_stiff gels_ allowed to polymerize between plate_ test conducted 20221027_average of all stiff PAH samples [Pa]', yerr = 'Loss Modulus_stiff gels_ allowed to polymerize between plate_ test conducted 20221027_STDDEV of all stiff PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'red')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_intermediate gels allowed to polymerize between plates_ test conducted 20221127_Average of all intermediate PAH samples [%]', y = 'Storage Modulus_intermediate gels_ allowed to polymerize between plate_ test conducted 20221127_average of all intermediate PAH samples [Pa]', data = df, color = 'black', marker = 'o', edgecolor = 'blue', label = 'G\u2032, intermediate PAH')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_intermediate gels allowed to polymerize between plates_ test conducted 20221127_Average of all intermediate PAH samples [%]', y = 'Loss Modulus_intermediate gels_ allowed to polymerize between plate_ test conducted 20221127_average of allintermediate PAH samples [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'blue', label = 'G\u2032\u2032, intermediate PAH')
#d_fn.errorbar(x = 'Shear Strain in percent_intermediate gels allowed to polymerize between plates_ test conducted 20221127_Average of all intermediate PAH samples [%]', y = 'Storage Modulus_intermediate gels_ allowed to polymerize between plate_ test conducted 20221127_average of all intermediate PAH samples [Pa]', yerr = 'Storage Modulus_intermediate gels_ allowed to polymerize between plate_ test conducted 20221127_STDDEV of all intermediate PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'blue')
#d_fn.errorbar(x = 'Shear Strain in percent_intermediate gels allowed to polymerize between plates_ test conducted 20221127_Average of all intermediate PAH samples [%]', y = 'Loss Modulus_intermediate gels_ allowed to polymerize between plate_ test conducted 20221127_average of allintermediate PAH samples [Pa]', yerr = 'Loss Modulus_intermediate gels_ allowed to polymerize between plate_ test conducted 20221127_STDDEV of all intermediate PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'blue')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_soft gels allowed to polymerize between plates_ test conducted 20221027_Average of all soft PAH samples [%]', y = 'Storage Modulus_soft gels_ allowed to polymerize between plate_ test conducted 20221027_average of all soft PAH samples [Pa]', data = df, color = 'black', marker = 'o', edgecolor = 'black', label = 'G\u2032, Soft PAH')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_soft gels allowed to polymerize between plates_ test conducted 20221027_Average of all soft PAH samples [%]', y = 'Loss Modulus_soft gels_ allowed to polymerize between plate_ test conducted 20221027_average of all soft PAH samples [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'black', label = 'G\u2032\u2032, Soft PAH')
#d_fn.errorbar(x = 'Shear Strain in percent_soft gels allowed to polymerize between plates_ test conducted 20221027_Average of all soft PAH samples [%]', y = 'Storage Modulus_soft gels_ allowed to polymerize between plate_ test conducted 20221027_average of all soft PAH samples [Pa]', yerr = 'Storage Modulus_soft gels_ allowed to polymerize between plate_ test conducted 20221027_STDDEV of all soft PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'black')
#d_fn.errorbar(x = 'Shear Strain in percent_soft gels allowed to polymerize between plates_ test conducted 20221027_Average of all soft PAH samples [%]', y = 'Loss Modulus_soft gels_ allowed to polymerize between plate_ test conducted 20221027_average of all soft PAH samples [Pa]', yerr = 'Loss Modulus_soft gels_ allowed to polymerize between plate_ test conducted 20221027_STDDEV of all soft PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'black')

#######################################SOFT VISCOELASTIC GEL ATTEMPT 1-8########################
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample1 [%]', y = ' Storage Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample1 [Pa]', data = df, color = 'orange', marker = 'o', edgecolor = 'orange', label = 'G\u2032,  Soft Viscoelastic 1')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample1 [%]', y = 'Loss Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample1 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'orange', label = 'G\u2032\u2032,  Soft Viscoelastic 1')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample2 [%]', y = ' Storage Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample2 [Pa]', data = df, color = 'red', marker = 'o', edgecolor = 'red', label = 'G\u2032,  Soft Viscoelastic 2')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample2 [%]', y = 'Loss Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample2 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'red', label = 'G\u2032\u2032,  Soft Viscoelastic 2')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample3 [%]', y = ' Storage Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample3 [Pa]', data = df, color = 'black', marker = 'o', edgecolor = 'black', label = 'G\u2032,  Soft Viscoelastic 3')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample3 [%]', y = 'Loss Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample3 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'black', label = 'G\u2032\u2032,  Soft Viscoelastic 3')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample4 [%]', y = ' Storage Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample4 [Pa]', data = df, color = 'c', marker = 'o', edgecolor = 'c', label = 'G\u2032,  Soft Viscoelastic 4')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample4 [%]', y = 'Loss Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample4 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'c', label = 'G\u2032\u2032,  Soft Viscoelastic 4')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample5 [%]', y = ' Storage Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample5 [Pa]', data = df, color = 'g', marker = 'o', edgecolor = 'g', label = 'G\u2032,  Soft Viscoelastic 5')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample5 [%]', y = 'Loss Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample5 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'g', label = 'G\u2032\u2032,  Soft Viscoelastic 5')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample6 [%]', y = ' Storage Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample6 [Pa]', data = df, color = 'yellow', marker = 'o', edgecolor = 'yellow', label = 'G\u2032,  Soft Viscoelastic 6')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample6 [%]', y = 'Loss Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample6 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'yellow', label = 'G\u2032\u2032,  Soft Viscoelastic 6')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample7 [%]', y = ' Storage Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample7 [Pa]', data = df, color = 'brown', marker = 'o', edgecolor = 'brown', label = 'G\u2032,  Soft Viscoelastic 7')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample7 [%]', y = 'Loss Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample7 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'brown', label = 'G\u2032\u2032,  Soft Viscoelastic 7')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample8 [%]', y = ' Storage Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample8 [Pa]', data = df, color = 'purple', marker = 'o', edgecolor = 'purple', label = 'G\u2032,  Soft Viscoelastic 8')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample8 [%]', y = 'Loss Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample8 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'purple', label = 'G\u2032\u2032,  Soft Viscoelastic 8')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample9 [%]', y = ' Storage Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample9 [Pa]', data = df, color = 'pink', marker = 'o', edgecolor = 'pink', label = 'G\u2032, Soft Viscoelastic 9')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_viscoelastic soft gels allowed to polymerize between plates_ test conducted 20221103_sample9 [%]', y = 'Loss Modulus_viscoelastic soft gels_ allowed to polymerize between plate_constant frequency 1 Hz_test conducted 20221103_sample9 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'pink', label = 'G\u2032\u2032,  Soft Viscoelastic 9')
####################ABERAGE SOFT VISCOELASTIC OF SAMPLE SET #1########################
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_soft viscoelastic gels allowed to polymerize between plates_ test conducted 20221103_Average of all soft viscoelastic PAH samples [%]', y = 'Storage Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221103_average of all soft viscoelastic PAH samples [Pa]', data = df, color = 'red', marker = 'o', edgecolor = 'red', label = 'G\u2032, Soft Viscoelastic PAH')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_soft viscoelastic gels allowed to polymerize between plates_ test conducted 20221103_Average of all soft viscoelastic PAH samples [%]', y = 'Loss Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221103_average of all soft viscoelastic PAH samples [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'red', label = 'G\u2032\u2032, Soft Viscoelastic PAH')
#d_fn.errorbar(x = 'Shear Strain in percent_soft viscoelastic gels allowed to polymerize between plates_ test conducted 20221103_Average of all soft viscoelastic PAH samples [%]', y = 'Storage Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221103_average of all soft viscoelastic PAH samples [Pa]', yerr = 'Storage Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221103_STDDEV of all soft viscoelastic PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'red')
#d_fn.errorbar(x = 'Shear Strain in percent_soft viscoelastic gels allowed to polymerize between plates_ test conducted 20221103_Average of all soft viscoelastic PAH samples [%]', y = 'Loss Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221103_average of all soft viscoelastic PAH samples [Pa]', yerr = 'Loss Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221103_STDDEV of all soft viscoelastic PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'red')
####################ABERAGE SOFT VISCOELASTIC OF SAMPLE SET #2########################
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_stiff viscoelastic gels allowed to polymerize between plates_ test conducted 20221107_Average of all stiff viscoelastic PAH samples [%]', y = 'Storage Modulus_stiff viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221107_average of all stiff viscoelastic PAH samples [Pa]', data = df, color = 'red', marker = 'o', edgecolor = 'red', label = 'G\u2032, Stiff Viscoelastic PAH')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_stiff viscoelastic gels allowed to polymerize between plates_ test conducted 20221107_Average of all stiff viscoelastic PAH samples [%]', y = 'Loss Modulus_stiff viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221107_average of all stiff viscoelastic PAH samples [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'red', label = 'G\u2032\u2032, Stiff Viscoelastic PAH')
#d_fn.errorbar(x = 'Shear Strain in percent_stiff viscoelastic gels allowed to polymerize between plates_ test conducted 20221107_Average of all stiff viscoelastic PAH samples [%]', y = 'Storage Modulus_stiff viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221107_average of all stiff viscoelastic PAH samples [Pa]', yerr = 'Storage Modulus_stiff viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221107_STDDEV of all stiff viscoelastic PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'red')
#d_fn.errorbar(x = 'Shear Strain in percent_stiff viscoelastic gels allowed to polymerize between plates_ test conducted 20221107_Average of all stiff viscoelastic PAH samples [%]', y = 'Loss Modulus_stiff viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221107_average of all stiff viscoelastic PAH samples [Pa]', yerr = 'Loss Modulus_stiff viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221107_STDDEV of all stiff viscoelastic PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'red')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_intermediate viscoelastic gels allowed to polymerize between plates_ test conducted 20221129_Average of all intermediate viscoelastic PAH samples [%]', y = 'Storage Modulus_intermediate viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221129_average of all intermediate viscoelastic PAH samples [Pa]', data = df, color = 'blue', marker = 'o', edgecolor = 'blue', label = 'G\u2032, Intermediate Viscoelastic PAH')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_intermediate viscoelastic gels allowed to polymerize between plates_ test conducted 20221129_Average of all intermediate viscoelastic PAH samples [%]', y = 'Loss Modulus_intermediate viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221129_average of all intermediate viscoelastic PAH samples [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'blue', label = 'G\u2032\u2032, Intermediate Viscoelastic PAH')
#d_fn.errorbar(x = 'Shear Strain in percent_intermediate viscoelastic gels allowed to polymerize between plates_ test conducted 20221129_Average of all intermediate viscoelastic PAH samples [%]', y = 'Storage Modulus_intermediate viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221129_average of all intermediate viscoelastic PAH samples [Pa]', yerr = 'Storage Modulus_intermediate gels_ allowed to polymerize between plate_ test conducted 20221129_STDDEV of all intermediate viscoelastic  PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'blue')
#d_fn.errorbar(x = 'Shear Strain in percent_intermediate viscoelastic gels allowed to polymerize between plates_ test conducted 20221129_Average of all intermediate viscoelastic PAH samples [%]', y = 'Loss Modulus_intermediate viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221129_average of all intermediate viscoelastic PAH samples [Pa]', yerr = 'Loss Modulus_intermediate gels_ allowed to polymerize between plate_ test conducted 20221129_STDDEV of all intermediate PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'blue')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_soft viscoelastic gels allowed to polymerize between plates_ test conducted 20221103_Average of all soft viscoelastic PAH samples2 [%]', y = 'Storage Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221103_average of all soft viscoelastic PAH samples2 [Pa]', data = df, color = 'black', marker = 'o', edgecolor = 'black', label = 'G\u2032, Soft Viscoelastic PAH')
#d_fn = sns.scatterplot(x = 'Shear Strain in percent_soft viscoelastic gels allowed to polymerize between plates_ test conducted 20221103_Average of all soft viscoelastic PAH samples2 [%]', y = 'Loss Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221103_average of all soft viscoelastic PAH samples2 [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'black', label = 'G\u2032\u2032, Soft Viscoelastic PAH')
#d_fn.errorbar(x = 'Shear Strain in percent_soft viscoelastic gels allowed to polymerize between plates_ test conducted 20221103_Average of all soft viscoelastic PAH samples2 [%]', y = 'Storage Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221103_average of all soft viscoelastic PAH samples2 [Pa]', yerr = 'Storage Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221103_STDDEV of all soft viscoelastic PAH samples2 [Pa]', fmt='none', data = df,label='_hidden',color= 'black')
#d_fn.errorbar(x = 'Shear Strain in percent_soft viscoelastic gels allowed to polymerize between plates_ test conducted 20221103_Average of all soft viscoelastic PAH samples2 [%]', y = 'Loss Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221103_average of all soft viscoelastic PAH samples2 [Pa]', yerr = 'Loss Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ test conducted 20221103_STDDEV of all soft viscoelastic PAH samples2 [Pa]', fmt='none', data = df,label='_hidden',color= 'black')

###########################AVERAGE SOFT, INTERMEDIATE, STIFF VISCOELASTIC OF FREQUENCY TEST###########################
#d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_soft viscoelastic gels allowed to polymerize between plates_ test conducted 20221106_average of all soft PAH samples [rad/s]', y = 'Storage Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221106_average of all soft viscoelastic PAH samples [Pa]', data = df, color = 'black', marker = 'o', edgecolor = 'black', label = 'G\u2032, Soft Viscoelastic PAH')
#d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_soft viscoelastic gels allowed to polymerize between plates_ test conducted 20221106_average of all soft PAH samples [rad/s]', y = 'Loss Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221106_average of all soft viscoelastic PAH samples [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'black', label = 'G\u2032\u2032, Soft Viscoelastic PAH')
#d_fn.errorbar(x = 'Frequency sweep_0.1-200 rads/s_soft viscoelastic gels allowed to polymerize between plates_ test conducted 20221106_average of all soft PAH samples [rad/s]', y = 'Storage Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221106_average of all soft viscoelastic PAH samples [Pa]', yerr = 'Storage Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221106_STDDEV of all soft viscoelastic PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'black')
#d_fn.errorbar(x = 'Frequency sweep_0.1-200 rads/s_soft viscoelastic gels allowed to polymerize between plates_ test conducted 20221106_average of all soft PAH samples [rad/s]', y = 'Loss Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221106_average of all soft viscoelastic PAH samples [Pa]', yerr = 'Loss Modulus_soft viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221106_STDDEV of all soft viscoelastic PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'black')
#d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_intermediate viscoelastic gels allowed to polymerize between plates_ test conducted 20221129_average of all intermediate PAH samples [rad/s]', y = 'Storage Modulus_intermediate viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221129_average of all intermediate viscoelastic PAH samples [Pa]', data = df, color = 'black', marker = 'o', edgecolor = 'blue', label = 'G\u2032, Intermediate viscoelastic PAH')
#d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_intermediate viscoelastic gels allowed to polymerize between plates_ test conducted 20221129_average of all intermediate PAH samples [rad/s]', y = 'Loss Modulus_intermediate viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221129_average of all intermediate viscoelastic PAH samples [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'blue', label = 'G\u2032\u2032, Intermediate viscoelastic PAH')
#d_fn.errorbar(x = 'Frequency sweep_0.1-200 rads/s_intermediate viscoelastic gels allowed to polymerize between plates_ test conducted 20221129_average of all intermediate PAH samples [rad/s]', y = 'Storage Modulus_intermediate viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221129_average of all intermediate viscoelastic PAH samples [Pa]', yerr = 'Storage Modulus_intermediate viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221129_STDDEV of all intermediate viscoelastic PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'blue')
#d_fn.errorbar(x = 'Frequency sweep_0.1-200 rads/s_intermediate viscoelastic gels allowed to polymerize between plates_ test conducted 20221129_average of all intermediate PAH samples [rad/s]', y = 'Loss Modulus_intermediate viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221129_average of all intermediate viscoelastic PAH samples [Pa]', yerr = 'Loss Modulus_intermediate viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221129_STDDEV of all intermediate viscoelastic PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'blue')
#d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_stiff viscoelastic gels allowed to polymerize between plates_ test conducted 20221108_average of all stiff PAH samples [rad/s]', y = 'Storage Modulus_stiff viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221108_average of all stiff viscoelastic PAH samples [Pa]', data = df, color = 'red', marker = 'o', edgecolor = 'red', label = 'G\u2032, Stiff Viscoelastic PAH')
#d_fn = sns.scatterplot(x = 'Frequency sweep_0.1-200 rads/s_stiff viscoelastic gels allowed to polymerize between plates_ test conducted 20221108_average of all stiff PAH samples [rad/s]', y = 'Loss Modulus_stiff viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221108_average of all stiff viscoelastic PAH samples [Pa]', data = df, color = 'none', marker = 'o', edgecolor = 'red', label = 'G\u2032\u2032, Stiff Viscoelastic PAH')
#d_fn.errorbar(x = 'Frequency sweep_0.1-200 rads/s_stiff viscoelastic gels allowed to polymerize between plates_ test conducted 20221108_average of all stiff PAH samples [rad/s]', y = 'Storage Modulus_stiff viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221108_average of all stiff viscoelastic PAH samples [Pa]', yerr = 'Storage Modulus_stiff viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221108_STDDEV of all stiff viscoelastic PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'red')
#d_fn.errorbar(x = 'Frequency sweep_0.1-200 rads/s_stiff viscoelastic gels allowed to polymerize between plates_ test conducted 20221108_average of all stiff PAH samples [rad/s]', y = 'Loss Modulus_stiff viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221108_average of all stiff viscoelastic PAH samples [Pa]', yerr = 'Loss Modulus_stiff viscoelastic gels_ allowed to polymerize between plate_ constant strain 1%_test conducted 20221108_STDDEV of all stiff viscoelastic PAH samples [Pa]', fmt='none', data = df,label='_hidden',color= 'red')

plt.legend(bbox_to_anchor = (1, 1), borderaxespad = 1)

#d_fn.set_xlabel('Angular frequency, \u03C9 (rads/s)', fontsize = 14)
d_fn.set_xlabel('Shear strain, \u03B3 (%)', fontsize = 14)
d_fn.set_ylabel('Storage Modulus, Loss Modulus \n $G\u2032, G\u2032\u2032$ (kPa)', fontsize = 14)

d_fn.tick_params(labelsize = 12)
#limits for frequency change, keep same for strain sweep
#plt.xlim(0.005, 100)
#plt.ylim(.1, 150000)
# limits for shear strain curve
plt.xlim(0.05, 300)
plt.ylim(.1, 150000)

plt.xscale('log')
plt.yscale('log')
print(type(d_fn))
d_fn.figure.tight_layout()
plt.savefig("SMLMVsfrequency.pdf", bbox_inches='tight', format="pdf")

plt.show()

